

use glfw::ffi;


#[repr(i32)]
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
pub enum Action {
    Release = ffi::GLFW_RELEASE,
    Press = ffi::GLFW_PRESS,
    Repeat = ffi::GLFW_REPEAT,
}


#[repr(i32)]
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
pub enum MouseButton {
    /// The left mouse button. A `MouseButtonLeft` alias is provided to improve clarity.
    Button1 = ffi::GLFW_MOUSE_BUTTON_1,
    /// The right mouse button. A `MouseButtonRight` alias is provided to improve clarity.
    Button2 = ffi::GLFW_MOUSE_BUTTON_2,
    /// The middle mouse button. A `MouseButtonMiddle` alias is provided to improve clarity.
    Button3 = ffi::GLFW_MOUSE_BUTTON_3,
    Button4 = ffi::GLFW_MOUSE_BUTTON_4,
    Button5 = ffi::GLFW_MOUSE_BUTTON_5,
    Button6 = ffi::GLFW_MOUSE_BUTTON_6,
    Button7 = ffi::GLFW_MOUSE_BUTTON_7,
    Button8 = ffi::GLFW_MOUSE_BUTTON_8,
}

#[repr(i32)]
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]

pub enum Key {
    Space = ffi::GLFW_KEY_SPACE,
    Apostrophe = ffi::GLFW_KEY_APOSTROPHE,
    Comma = ffi::GLFW_KEY_COMMA,
    Minus = ffi::GLFW_KEY_MINUS,
    Period = ffi::GLFW_KEY_PERIOD,
    Slash = ffi::GLFW_KEY_SLASH,
    Num0 = ffi::GLFW_KEY_0,
    Num1 = ffi::GLFW_KEY_1,
    Num2 = ffi::GLFW_KEY_2,
    Num3 = ffi::GLFW_KEY_3,
    Num4 = ffi::GLFW_KEY_4,
    Num5 = ffi::GLFW_KEY_5,
    Num6 = ffi::GLFW_KEY_6,
    Num7 = ffi::GLFW_KEY_7,
    Num8 = ffi::GLFW_KEY_8,
    Num9 = ffi::GLFW_KEY_9,
    Semicolon = ffi::GLFW_KEY_SEMICOLON,
    Equal = ffi::GLFW_KEY_EQUAL,
    A = ffi::GLFW_KEY_A,
    B = ffi::GLFW_KEY_B,
    C = ffi::GLFW_KEY_C,
    D = ffi::GLFW_KEY_D,
    E = ffi::GLFW_KEY_E,
    F = ffi::GLFW_KEY_F,
    G = ffi::GLFW_KEY_G,
    H = ffi::GLFW_KEY_H,
    I = ffi::GLFW_KEY_I,
    J = ffi::GLFW_KEY_J,
    K = ffi::GLFW_KEY_K,
    L = ffi::GLFW_KEY_L,
    M = ffi::GLFW_KEY_M,
    N = ffi::GLFW_KEY_N,
    O = ffi::GLFW_KEY_O,
    P = ffi::GLFW_KEY_P,
    Q = ffi::GLFW_KEY_Q,
    R = ffi::GLFW_KEY_R,
    S = ffi::GLFW_KEY_S,
    T = ffi::GLFW_KEY_T,
    U = ffi::GLFW_KEY_U,
    V = ffi::GLFW_KEY_V,
    W = ffi::GLFW_KEY_W,
    X = ffi::GLFW_KEY_X,
    Y = ffi::GLFW_KEY_Y,
    Z = ffi::GLFW_KEY_Z,
    LeftBracket = ffi::GLFW_KEY_LEFT_BRACKET,
    Backslash = ffi::GLFW_KEY_BACKSLASH,
    RightBracket = ffi::GLFW_KEY_RIGHT_BRACKET,
    GraveAccent = ffi::GLFW_KEY_GRAVE_ACCENT,
    World1 = ffi::GLFW_KEY_WORLD_1,
    World2 = ffi::GLFW_KEY_WORLD_2,

    Escape = ffi::GLFW_KEY_ESCAPE,
    Enter = ffi::GLFW_KEY_ENTER,
    Tab = ffi::GLFW_KEY_TAB,
    Backspace = ffi::GLFW_KEY_BACKSPACE,
    Insert = ffi::GLFW_KEY_INSERT,
    Delete = ffi::GLFW_KEY_DELETE,
    Right = ffi::GLFW_KEY_RIGHT,
    Left = ffi::GLFW_KEY_LEFT,
    Down = ffi::GLFW_KEY_DOWN,
    Up = ffi::GLFW_KEY_UP,
    PageUp = ffi::GLFW_KEY_PAGE_UP,
    PageDown = ffi::GLFW_KEY_PAGE_DOWN,
    Home = ffi::GLFW_KEY_HOME,
    End = ffi::GLFW_KEY_END,
    CapsLock = ffi::GLFW_KEY_CAPS_LOCK,
    ScrollLock = ffi::GLFW_KEY_SCROLL_LOCK,
    NumLock = ffi::GLFW_KEY_NUM_LOCK,
    PrintScreen = ffi::GLFW_KEY_PRINT_SCREEN,
    Pause = ffi::GLFW_KEY_PAUSE,
    F1 = ffi::GLFW_KEY_F1,
    F2 = ffi::GLFW_KEY_F2,
    F3 = ffi::GLFW_KEY_F3,
    F4 = ffi::GLFW_KEY_F4,
    F5 = ffi::GLFW_KEY_F5,
    F6 = ffi::GLFW_KEY_F6,
    F7 = ffi::GLFW_KEY_F7,
    F8 = ffi::GLFW_KEY_F8,
    F9 = ffi::GLFW_KEY_F9,
    F10 = ffi::GLFW_KEY_F10,
    F11 = ffi::GLFW_KEY_F11,
    F12 = ffi::GLFW_KEY_F12,
    F13 = ffi::GLFW_KEY_F13,
    F14 = ffi::GLFW_KEY_F14,
    F15 = ffi::GLFW_KEY_F15,
    F16 = ffi::GLFW_KEY_F16,
    F17 = ffi::GLFW_KEY_F17,
    F18 = ffi::GLFW_KEY_F18,
    F19 = ffi::GLFW_KEY_F19,
    F20 = ffi::GLFW_KEY_F20,
    F21 = ffi::GLFW_KEY_F21,
    F22 = ffi::GLFW_KEY_F22,
    F23 = ffi::GLFW_KEY_F23,
    F24 = ffi::GLFW_KEY_F24,
    F25 = ffi::GLFW_KEY_F25,
    Kp0 = ffi::GLFW_KEY_KP_0,
    Kp1 = ffi::GLFW_KEY_KP_1,
    Kp2 = ffi::GLFW_KEY_KP_2,
    Kp3 = ffi::GLFW_KEY_KP_3,
    Kp4 = ffi::GLFW_KEY_KP_4,
    Kp5 = ffi::GLFW_KEY_KP_5,
    Kp6 = ffi::GLFW_KEY_KP_6,
    Kp7 = ffi::GLFW_KEY_KP_7,
    Kp8 = ffi::GLFW_KEY_KP_8,
    Kp9 = ffi::GLFW_KEY_KP_9,
    KpDecimal = ffi::GLFW_KEY_KP_DECIMAL,
    KpDivide = ffi::GLFW_KEY_KP_DIVIDE,
    KpMultiply = ffi::GLFW_KEY_KP_MULTIPLY,
    KpSubtract = ffi::GLFW_KEY_KP_SUBTRACT,
    KpAdd = ffi::GLFW_KEY_KP_ADD,
    KpEnter = ffi::GLFW_KEY_KP_ENTER,
    KpEqual = ffi::GLFW_KEY_KP_EQUAL,
    LeftShift = ffi::GLFW_KEY_LEFT_SHIFT,
    LeftControl = ffi::GLFW_KEY_LEFT_CONTROL,
    LeftAlt = ffi::GLFW_KEY_LEFT_ALT,
    LeftSuper = ffi::GLFW_KEY_LEFT_SUPER,
    RightShift = ffi::GLFW_KEY_RIGHT_SHIFT,
    RightControl = ffi::GLFW_KEY_RIGHT_CONTROL,
    RightAlt = ffi::GLFW_KEY_RIGHT_ALT,
    RightSuper = ffi::GLFW_KEY_RIGHT_SUPER,
    Menu = ffi::GLFW_KEY_MENU,
    Unknown = ffi::GLFW_KEY_UNKNOWN,
}


    
        